Ghome/urls.py

from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',include('core.urls',namespace='core')),
    path('admin/', admin.site.urls),
    path('product/',include('product.urls',namespace='product')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('order/',include('order.urls',namespace='order')),
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import add_to_cart,cart,checkout,hx_menu_cart,update_cart,hx_cart_total,success


app_name='cart'
urlpatterns =[
    path('',cart,name='cart'),
    path('success/',success,name='success'),
    path('checkout/',checkout,name='checkout'),
    path('update_cart/<int:product_id>/<str:action>/',update_cart,name='update_cart'),
    path('<int:product_id>/',add_to_cart,name='add_to_cart'),
    path('hx_menu_cart/',hx_menu_cart,name='hx_menu_cart'),
    path('hx-cart-total/',hx_cart_total,name='hx_cart_total'),
    
]

cart/views.py
from django.shortcuts import render
from django.conf import settings
from django.contrib.auth.decorators import login_required
from .cart import Cart
from product.models import Product

# Create your views here.

def add_to_cart(request,product_id):
    cart= Cart(request)
    cart.add(product_id)
    return render(request,'cart/partials/menu_cart.html')

def cart(request):
    cart= Cart(request)

    print(cart)
    for item in cart:
        print(item)
    return render(request,'cart/cart.html')

def success(request):
    return render(request,'cart/success.html')

def update_cart(request,product_id,action):
    cart= Cart(request)

    if action == 'increment':
        cart.add(product_id,1,True)
    else:
        cart.add(product_id,-1,True)
    
    product= Product.objects.get(pk=product_id)
    quantity= cart.get_item(product_id)

    if quantity:
        quantity= quantity['quantity']

        item= {
            'product':{
                'id':product.id,
                'name':product.name,
                'image':product.image,
                'get_thumbnail':product.get_thumbnail(),
                'price':product.price,
            },
            'total_price':(quantity * product.price) / 100,
            'quantity':quantity,
        }
    else:
        item= None
        
    context={'item':item}

    response= render(request,'cart/partials/cart_item.html',context)
    response['HX-Trigger']= 'update-menu-cart'
    return response

@login_required
def checkout(request):
    pub_key= settings.STRIPE_API_KEY_PUBLISHABLE
    context={'pub_key':pub_key}
    return render(request,'cart/checkout.html',context)

def hx_menu_cart(request):
    return render(request,'cart/partials/menu_cart.html')

def hx_cart_total(request):
    return render(request,'cart/partials/cart_total.html')

cart/templates/cart/cart.html
{% extends 'core/base.html' %}

{% block title %}Cart{%endblock title %}

{% block content %}

    <div class="max-w-6xl mx-auto flex flex-wrap items-start py-6 px-6 xl:px-0">
        <div class="products w-full lg:w-3/4">
            {% for item in cart %}
                {% include 'cart/partials/cart_item.html' %}
            {% endfor %}
        </div>

        <div class="summary w-full md:w-1/4 p-6 bg-gray-100 rounded-xl mt-3">
            <h2 class="uppercase text-lg mb-5">Summary</h2>

            <div class="mb-6 flex justify-between">
                <span class="font-semibold">Total</span>

                <span
                    hx-get="{% url 'cart:hx_cart_total' %}"
                    hx-trigger="update-menu-cart from:body"
                    hx-swap="innerHTML"
                >
                {% include 'cart/partials/cart_total.html' %}
                </span>
            </div>
            <a href="{%url 'cart:checkout' %}" class="inline-block px-8 py-4 rounded-xl bg-purple-500 hover:bg-purple-700 text-white">Checkout</a>
        </div>
    </div>

{% endblock content %}

cart/templates/cart/checkout.html
{% extends 'core/base.html' %}

{% block title %}Checkout{%endblock title %}

{% block content %}

    <div class="max-w-6xl mx-auto flex flex-wrap items-start py-6 px-6 xl:px-0">
        <div class="products w-full lg:w-3/4">
            <h1 class="mb-5 text-3xl">Checkout</h1>
            <div class="w-full md:pr-6">
                <div class="mb-6 p-6 bg-gray-100 rounded-xl">
                    <h2 class="mb-5 uppercase text-lg">Shipping Information</h2>

                    <div class="flex space-x-6">
                        <div class="w-1/2 mb-4">
                            <label class="inline-block mb-2">First Name</label>
                            <input name="first_name" type="text" class="w-full p-5 rounded-xl" value=" {{request.user.first_name}}">
                        </div>

                        <div class="w-1/2 mb-4">
                            <label class="inline-block mb-2">Last Name</label>
                            <input name="last_name" type="text" class="w-full p-5 rounded-xl" value=" {{request.user.last_name}}">
                        </div>

                    </div>

                    <div class="mb-4">
                        <label class="inline-block mb-2">Address</label>
                        <input name="address" type="text" class="w-full p-5 rounded-xl">
                    </div>

                    <div class="flex space-x-6">
                        <div class="w-1/2 mb-4">
                            <label class="inline-block mb-2">zip code</label>
                            <input name="zipcode" type="text" class="w-full p-5 rounded-xl">
                        </div>


                        <div class="w-1/2 mb-4">
                            <label class="inline-block mb-2">place</label>
                            <input name="place" type="text" class="w-full p-5 rounded-xl">
                        </div>
                    </div>
                </div>

                <div class="mb-6 p-6 bg-gray-100 rounded-xl">
                    <h2 class="mb-5 uppercase text-lg">Contact Information</h2>
                    <div class="mb-4">
                        <label class="inline-block mb-2">Email</label>
                        <input name="email" type="email" class="w-full p-5 rounded-xl" value=" {{request.user.email}}">
                    </div>

                    <div class="mb-4">
                        <label class="inline-block mb-2">Phone</label>
                        <input name="phone" type="phone" class="w-full p-5 rounded-xl">
                    </div>
                </div>

                <!-- Error messages -->
                <div class="mb-6 p-6 bg-gray-100 rounded-xl" id="errors">
                    
                </div>
            </div>
        </div>
    

        <div class="summary w-full md:w-1/4 p-6 bg-gray-100 rounded-xl mt-3">
            <h2 class="uppercase text-lg mb-5">Summary</h2>

            <div class="mb-6 flex justify-between">
                <span class="font-semibold">Total</span>
                <span>${{cart.get_total_cost}}</span>
            </div>
            <button
            onclick="buy(event)" class="inline-block px-8 py-4 rounded-xl bg-purple-500 
            hover:bg-purple-700 text-white">
                Confirm Checkout
            </button>
        </div>
    </div>

{% endblock content %}

{% block scripts %}

<script type="application/javascript" src="https://js.stripe.com/v3/"></script>

<script>
    let el= document.querySelector('#errors') 

    function validateForm(data){
        let errors=[]

        if(data.first_name == ''){
            errors.push('First name is empty!')
        }

        if(data.last_name == ''){
            errors.push('Last name is empty!')
        }

        if(data.email == ''){
            errors.push('Email is empty!')
        }

        if(data.address == ''){
            errors.push('Address is empty!')
        }

        if(data.phone == ''){
            errors.push('Phone is empty!')
        }

        if(data.zipcode == ''){
            errors.push('Zipcode is empty!')
        }

        if(data.place == ''){
            errors.push('Place is empty!')
        }

        if (errors.length >0 ) {
            let html= '<ul>';
            errors.forEach((error) => {
                html += '<li>' + error + '</li>';
            })
            el.innerHTML= html + '</ul>';
        }else{
            el.innerHTML= '';
        }
        return errors
    }

    function buy(event){
        event.preventDefault()

        let data= {
            'first_name':document.querySelector('input[name=first_name]').value,
            'last_name':document.querySelector('input[name=last_name]').value,
            'email':document.querySelector('input[name=email]').value,
            'phone':document.querySelector('input[name=phone]').value,
            'address':document.querySelector('input[name=address]').value,
            'zipcode':document.querySelector('input[name=zipcode]').value,
            'place':document.querySelector('input[name=place]').value,
        }

        let errors= validateForm(data)

        if(errors.length){
            console.log('Errors',errors)
        }else{
            var stripe= Stripe('{{pub_key}}')

            fetch('/order/start_order/',{
                method:'POST',
                headers:{
                    'Content-Type':'application/json',
                    'X-CSRFToken':'{{csrf_token}}'
                },
                credentials:'same-origin',
                body: JSON.stringify(data)
            })
            .then(function(response){
                return response.json()
            })
            .then(function(session){
                return stripe.redirectToCheckout({sessionId:session.session.id})
            })
            .then(function(result){
                if(result.error){
                    alert(result.error.message)
                }
            })
            .catch(function(error){
                console.log("Errors",error)
            })
        }

        return false
    }
</script>


{% endblock scripts %}

cart/templates/cart/success.html
{% extends 'core/base.html' %}

{% block title %}Checkout{%endblock title %}

{% block content %}

    <div class="max-w-6xl mx-auto flex flex-wrap items-start py-6 px-6 xl:px-0">
        <div class="products w-full lg:w-3/4">
            <h1 class="mb-5 text-3xl">Success</h1>

            <p>Thanks for making the purchase.</p>
        </div>
    </div>
{% endblock content %}