Ghome/urls.py

from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',include('core.urls',namespace='core')),
    path('admin/', admin.site.urls),
    path('product/',include('product.urls',namespace='product')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('order/',include('order.urls',namespace='order')),
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import add_to_cart,cart,checkout,hx_menu_cart,update_cart,hx_cart_total,success


app_name='cart'
urlpatterns =[
    path('',cart,name='cart'),
    path('success/',success,name='success'),
    path('checkout/',checkout,name='checkout'),
    path('update_cart/<int:product_id>/<str:action>/',update_cart,name='update_cart'),
    path('<int:product_id>/',add_to_cart,name='add_to_cart'),
    path('hx_menu_cart/',hx_menu_cart,name='hx_menu_cart'),
    path('hx-cart-total/',hx_cart_total,name='hx_cart_total'),
    
]

core/urls.py
from django.urls import path
from django.contrib.auth import views
from .views import home,shop,signup,myaccount,edit_myaccount

app_name='core'
urlpatterns =[
    path('',home,name='home'),
    path('shop/',shop,name='shop'),
    path('signup/',signup,name='signup'),
    path('login/',views.LoginView.as_view(template_name= 'core/login.html'),name='login'),
    path('logout/',views.LogoutView.as_view(),name='logout'),
    path('myaccount/',myaccount,name='myaccount'),
    path('myaccount/edit/',edit_myaccount,name='edit_myaccount'),

] 

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    first_name= forms.CharField(max_length=50,required=True)
    last_name= forms.CharField(max_length=50,required=True)
    email= forms.EmailField(max_length=255,required=True)

    class Meta:
        model= User
        fields=['username','first_name','last_name','email','password1','password2']

core/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.shortcuts import render,redirect
from django.db.models import Q
from .forms import SignupForm
from product.models import Product,Category

# Create your views here.

def signup(request):
    if request.method == 'POST':
        form= SignupForm(request.POST)

        if form.is_valid():
            user= form.save()

            login(request,user)
            return redirect('/')
        
    else:
        form= SignupForm()
    context={'form':form}   
    return render(request,'core/signup.html',context)

@login_required
def myaccount(request):
    return render(request,'core/myaccount.html')

@login_required
def edit_myaccount(request):

    if request.method == 'POST':
        print('post')
        first_name= request.POST.get('first_name')
        last_name= request.POST.get('last_name')
        username= request.POST.get('username')
        email= request.POST.get('email')
        
        user= request.user
        user.first_name= first_name
        user.last_name= last_name
        user.email= email
        user.username= username
        user.save()
        return redirect('core:myaccount')
    else:
        print('not post')

    return render(request,'core/edit_myaccount.html')

def home(request):
    products= Product.objects.all()[0:8]
    context={'products':products}
    return render(request,'core/home.html',context)

def shop(request):
    categories = Category.objects.all()
    products= Product.objects.all()

    active_category = request.GET.get('category','')

    if active_category:
        products= products.filter(category__slug=active_category)

    query = request.GET.get('query','')

    if query:
        products = products.filter(Q(name__icontains=query) | Q(description__icontains=query))

    context={'products':products,
             'categories':categories,
             'active_category':active_category}
    return render(request,'core/shop.html',context)

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script> 
    <title>{% block title %}{%endblock title %} | GoeyWebsite</title>
</head>
<body>
    <nav class="border-b border-gray-300">
        <div class="max-w-6xl mx-auto py-2 px-6 xl:px-0 flex items-center justify-between">
            <div class="manu-left flex items-center space-x-6">
                <a href="{% url 'core:home' %}" class="py-4 text-lg text-purple-500 font-semibold">Goey Home Logo</a>
                <ul class="flex items-center space-x-4">
                    <li><a href="{% url 'core:shop' %}">Shop</a></li>
                    <li><a href="#">About</a></li>

                    {% if request.user.is_authenticated %}
                    <li><a href="{% url 'core:logout' %}">Logout</a></li>
                    {% endif %}
                </ul>
            </div>

            <!-- Menu right -->
            <div class="menu-right flex items-center space-x-4">
                <a href="{% url 'core:myaccount' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
                      </svg>  
                <div
                    hx-get="{% url 'cart:hx_menu_cart' %}"
                    hx-trigger="update-menu-cart from:body"
                    hx-swap="innerHTML"
                    >

                    {% include 'cart/partials/menu_cart.html' %}
                </div>
            </div>
        </div>
    </nav>
    <!-- Main -->
    <main>
        {% block content %}
        {% endblock content %}
        
    </main>
    <!-- footer -->
    <footer class="bg-gray-100">
        <div class="max-w-6xl mx-auto py-10 px-6 xl:px-0 md:flex justify-between">
            <!-- footer left -->
            <div class="footer-left mb-12 md:mb-0">
                <h2 class="mb-5 uppercase text-lg">About us</h2>
                <p class="text-gray-700">Test test test</p>
            </div>
            <!-- footer right -->
            <div class="footer-right">
                <h2 class="mb-5 uppercase text-lg">Social Links</h2>
                <ul class="space-y-2">
                    <li><a href="" class="text-purple-500 hover:text-purple-800">Facebook</a></li>
                    <li><a href="" class="text-purple-500 hover:text-purple-800">Twitter</a></li>
                    <li><a href="" class="text-purple-500 hover:text-purple-800">Instagram</a></li>
                </ul>
            </div>

        </div>

    </footer>
    <script src="https://unpkg.com/htmx.org@1.7.0"></script>
    
    {% block scripts %}
    {% endblock scripts %}
</body>
</html>

core/templates/core/edit_myaccount.html
{% extends 'core/base.html' %}


{% block title %}Edit My account{%endblock title %}

{% block content %}

    <div class="max-w-6xl mx-auto p-6">
        <h1 class="mb-5 text-3xl">Edit Account</h1>
        <form method="POST" action=".">
            {% csrf_token %}
            <div>
                <label>First Name</label>
                <input name="first_name" value="{{request.user.first_name}}" type="text" class="w-full mt-2 py-4 px-6 bg-gray-100 rounded-xl">
            </div>

            <div>
                <label>Last Name</label>
                <input name="last_name" value="{{request.user.last_name}}" type="text" class="w-full mt-2 py-4 px-6 bg-gray-100 rounded-xl">
            </div>

            <div>
                <label>Username</label>
                <input name="username" value="{{request.user.username}}" type="text" class="w-full mt-2 py-4 px-6 bg-gray-100 rounded-xl">
            </div>

            <div>
                <label>Email</label>
                <input name="email" value="{{request.user.email}}" type="email" class="w-full mt-2 py-4 px-6 bg-gray-100 rounded-xl">
            </div>

            <div>
                <button class="py-4 px-6 text-white rounded-xl bg-purple-500">Submit</button>
            </div>

        </form>
       

    </div>

    {% endblock content %}

core/templates/core/home.html
{% extends 'core/base.html' %}

{% block title %}Welcome{%endblock title %}
{% block content %}
        
    <header class="px-6 py-10 lg:py-20 bg-purple-500">
        <div class="max-w-3xl mx-auto text-center">
            <p class="mb-2 text-3xl lg:text-5xl text-white">Welcome to Goey HomePage</p>
            <p class="mb-10 text-white">We sell Coffee powder and SMC Accounting solution</p>

            <a href="{% url 'core:shop' %}" class="inline-block px-8 py-4 rounded-xl bg-white text-purple-500 hover:bg-gray-200">Shopping</a>
        </div>

    </header>

    <div class="max-w-6xl mx-auto py-2 px-6 xl:px-0">
        <div class="products flex items-center flex-wrap">
            {% for product in products %}
                {% include 'product/partials/product_list_item.html' %}
            {% endfor %}

        </div>

    </div>
{% endblock content %}

core/templates/core/login.html
{% extends 'core/base.html' %}


{% block title %}Login{%endblock title %}

{% block content %}

    <div class="max-w-lg mx-auto flex flex-wrap p-6">
        <div class="w-full bg-gray-100 p-6 rounded-xl">
            <h1 class="mb-6 text-xl">Signup</h1>
            <form method="post" action="." class="space-y-3">
                {% csrf_token %}
                <div>
                    <label>Username</label>
                    <input type="text" name="username" class="w-full mt-2 py-4 px-6 bg-white rounded-xl">
                </div>

                <div>
                    <label>Password</label>
                    <input type="password1" name="password" class="w-full mt-2 py-4 px-6 bg-white rounded-xl">
                </div>

                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="p-6 bg-red-200 text-red-800 rounded-xl">
                                <p>{{error|escape}}</p>
                            </div>
                        {% endfor %}
                    {% endfor %}

                    {% for error in form.non_field_errors %}
                        <div class="p-6 bg-red-200 text-red-800 rounded-xl">
                            <p>{{error|escape}}</p>
                        </div>
                    {% endfor %}
                {% endif %}

                <div>
                    <button class="py-4 px-6 rounded-xl text-white bg-purple-500 hover:bg-purple-700">Login</button>
                </div>

            </form>
        </div>

    </div>

{% endblock content %}

core/templates/core/myaccount.html
{% extends 'core/base.html' %}


{% block title %}My account{%endblock title %}

{% block content %}

    <div class="max-w-6xl mx-auto p-6">
        
        <h1 class="mb-5 text-3xl">My account</h1>

        <div class="mb-6">
            <strong>Name: {{request.user.get_full_name}}</strong><br>
            <strong>Username: {{request.user.username}}</strong><br>
            <strong>Email: {{request.user.email}}</strong><br>

            <a href="{% url 'core:edit_myaccount'%}" class="inline-block mt-4 py-4 px-6 text-white rounded-xl bg-purple-500">Edit</a>
        </div>
        <hr>
        <h2 class="my-6 text-xl">My orders</h2>

        {% for order in request.user.orders.all %}
            <div class="w-full mb-6 p-6 flex flex-wrap bg-gray-100 rounded-xl">
                <div class="mb-6 flex justify-between">
                    <a href="#">Order id: {{order.id}}</a>
                </div>

                <div class="mb-6 w-full">
                    {% for item in order.items.all %}
                    <div class="product mb-6 flex pr-6">
                        <a href="#" class="w-1/4">
                            <img class="hover:shadow-lg rounded-xl" src="{{item.product.get_thumbnail}}">
                        </a>

                        <div class="w-3/4 pl-6">
                            <div class="flex justify-between">
                                <a href="#" class="text-lg">{{item.product.name}}</a>
                                <p class="mb-6 pt-1 text-gray-400">${{ item.get_total_price }}</p>
                            </div>

                            <hr>

                            <div class="mt-6">
                                Quantity:{{item.quantity}}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div>
                    <p class="text-lg">Date:{{order.created_at}}</p>
                    <p class="text-lg">Total: ${{ order.get_total_price }}</p>
                </div>
            </div>
        {% endfor %}
    </div>

    {% endblock content %}

core/templates/core/shop.html
{% extends 'core/base.html' %}

{% block title %}Shop{%endblock title %}

{% block content %}

    <div class="max-w-6xl mx-auto flex flex-wrap items-start py-6 px-6 xl:px-0">
        <div class="filters w-full lg:w-1/4">
            <h class="mb-3 text-xl uppercase">search</h>

            <form method="get" action=".">
                <div class="flex">
                    <input type="text" name="query" class="p-4 bg-gray-100 border-0" placeholder="Search...">

                    <button class="p-4 bg-gray-100 border-0">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
                        </svg>
                          
                    </button>

                </div>
            </form>
            <h3 class="mt-6 mb-3 text-xl uppercase">Categories</h3>
            <ul class="space-y-3">
                <li><a href="{% url 'core:shop'%}" class="{% if not active_category%}text-purple-500 {% else %} text-gray-500 {% endif %}">All</a></li>
                {% for category in categories %}
                    <li><a href="{% url 'core:shop'%}?category={{category.slug}}" class="{% if category.slug == active_category%}text-purple-500 {% else %} text-gray-500 {% endif %}">{{category.name}}</a></li>
                {% endfor %}
            </ul>
        </div>
        <div class="products w-full lg:w-3/4 flex items-center flex-wrap">
            {% for product in products %}
                {% include 'product/partials/product_list_item.html' %}
            {% endfor %}

        </div>

    </div>
{% endblock content %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Signup{%endblock title %}

{% block content %}

    <div class="max-w-lg mx-auto flex flex-wrap p-6">
        <div class="w-full bg-gray-100 p-6 rounded-xl">
            <h1 class="mb-6 text-xl">Signup</h1>
            <form method="post" action="." class="space-y-3">
                {% csrf_token %}

                <div>
                    <label>Username</label>
                    <input type="text" name= "username" class="w-full mt-2 py-4 px-6 bg-white rounded-xl">
                </div>

                <div>
                    <label>First Name</label>
                    <input type="text" name= "first_name" class="w-full mt-2 py-4 px-6 bg-white rounded-xl">
                </div>

                <div>
                    <label>Last Name</label>
                    <input type="text" name= "last_name" class="w-full mt-2 py-4 px-6 bg-white rounded-xl">
                </div>

                <div>
                    <label>E-mail</label>
                    <input type="email" name= "email" class="w-full mt-2 py-4 px-6 bg-white rounded-xl">
                </div>

                <div>
                    <label>Password</label>
                    <input type="password1" name= "password1" class="w-full mt-2 py-4 px-6 bg-white rounded-xl">
                </div>

                <div>
                    <label>Password Confirmation</label>
                    <input type="password2" name= "password2"class="w-full mt-2 py-4 px-6 bg-white rounded-xl">
                </div>

                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="p-6 bg-red-200 text-red-800 rounded-xl">
                                <p>{{error|escape}}</p>
                            </div>
                        {% endfor %}
                    {% endfor %}

                    {% for error in form.non_field_errors %}
                        <div class="p-6 bg-red-200 text-red-800 rounded-xl">
                            <p>{{error|escape}}</p>
                        </div>
                    {% endfor %}
                {% endif %}

                <div>
                    <button class="py-4 px-6 rounded-xl text-white bg-purple-500 hover:bg-purple-700">Signup</button>
                </div>

            </form>
        </div>

    </div>

{% endblock content %}