Ghome/urls.py

from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',include('core.urls',namespace='core')),
    path('admin/', admin.site.urls),
    path('product/',include('product.urls',namespace='product')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('order/',include('order.urls',namespace='order')),
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import add_to_cart,cart,checkout,hx_menu_cart,update_cart,hx_cart_total,success


app_name='cart'
urlpatterns =[
    path('',cart,name='cart'),
    path('success/',success,name='success'),
    path('checkout/',checkout,name='checkout'),
    path('update_cart/<int:product_id>/<str:action>/',update_cart,name='update_cart'),
    path('<int:product_id>/',add_to_cart,name='add_to_cart'),
    path('hx_menu_cart/',hx_menu_cart,name='hx_menu_cart'),
    path('hx-cart-total/',hx_cart_total,name='hx_cart_total'),
    
]

product/urls.py
from django.urls import path
from . import views


app_name='product'
urlpatterns =[
    path('<slug:slug>/',views.product,name='product'),
    
]

product/models.py
from django.db import models
from django.core.files import File
from django.contrib.auth.models import User
from PIL import Image
from io import BytesIO

# Create your models here.
class Category(models.Model):
    name= models.CharField(max_length=255)
    slug= models.SlugField()

    class Meta:
        verbose_name_plural= "Categories"
        ordering= ('name',)
    
    def __str__(self):
        return self.name
    
class Product(models.Model):
    category= models.ForeignKey(Category,related_name='products',on_delete=models.CASCADE)
    name= models.CharField(max_length=255)
    slug= models.SlugField()
    description= models.TextField(null=True,blank=True)
    price= models.IntegerField()
    created_at= models.DateTimeField(auto_now_add=True)
    image= models.ImageField(upload_to='uploads/',blank=True,null=True)
    thumbnail= models.ImageField(upload_to='uploads/',blank=True,null=True)

    class Meta:
        ordering= ('-created_at',)
    
    def __str__(self):
        return self.name
    
    def get_display_price(self):
        return self.price / 100
    
    def get_thumbnail(self):
        if self.thumbnail:
            return self.thumbnail.url
        else:
            if self.image:
                self.thumbnail= self.make_thumbnail(self.image)
                self.save()
                return self.thumbnail.url
            else:
                return 'https://via.placeholder.com/240x240.jpg'
            
    def make_thumbnail(self,image,size=(300,300)):
        img= Image.open(image)
        img.convert('RGB')
        img.thumbnail(size)

        thumb_io= BytesIO()
        img.save(thumb_io,'JPEG',quality=85)

        thumbnail= File(thumb_io,name=image.name)

        return thumbnail

    def get_rating(self):
        reviews_total = 0

        for review in self.reviews.all():
            reviews_total += review.rating
        
        if reviews_total > 0:
            return reviews_total / self.reviews.count()
        
        return 0

    
class Review(models.Model):
    product= models.ForeignKey(Product,related_name='reviews',on_delete=models.CASCADE)
    rating= models.IntegerField(default=3)
    content= models.TextField()
    created_by= models.ForeignKey(User,related_name='reviews',on_delete=models.CASCADE)
    created_at= models.DateTimeField(auto_now_add=True)

product/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Product,Review

# Create your views here.
def product(request,slug):
    product= get_object_or_404(Product,slug=slug)

    if request.method == 'POST':
        rating= request.POST.get('rating',3)
        content= request.POST.get('content','')

        if content:
            reviews= Review.objects.filter(created_by=request.user,product=product)
            if reviews.count() > 0:
                review= reviews.first()
                review.rating= rating
                review.content= content
                review.save()
            else:
                review=Review.objects.create(
                    product=product,
                    rating=rating,
                    content=content,
                    created_by=request.user
                    )
            return redirect('product:product',slug=slug)
        
    context = {'product':product}
    return render(request,'product/product.html',context)

product/templates/product/product.html
{% extends 'core/base.html' %}

{% block title %}{{product.name}}{%endblock title %}

{% block content %}

    <div class="max-w-6xl mx-auto flex flex-wrap py-6 px-6 xl:px-0">
        <div class="images w-full mb-6 lg:mb-0 lg:w-3/5">
            <img calss="rounded-xl" src="{% if product.image %} {{product.image.url}} {% else %} https://via.placeholder.com/240x240.jpg {% endif %}">
        </div>

        <div class="information w-full lg:w-2/5 lg:p-6">
            <h1 class="text-2xl">{{product.name}}</h1>
            <p class="mt-1 text-gray-400">${{product.get_display_price}}</p>

            {% if product.get_rating > 0 %}
                <p class="mt-1 text-gray-400">Rating: {{product.get_rating}} / 6</p>
            {% endif %}

            {% if product.description %}
                <p class="mt-6 text-gray-700">{{product.description}}</p>
            {% endif %}
            <a href="#" class="mt-6 inline-block px-8 py-4 rounded-xl bg-purple-500 text-white hover:bg-purple-700"
            hx-get="{% url 'cart:add_to_cart' product.id %}"
            hx-target="#menu-cart-button"
            hx-swap="outerHTML"
            >
                Add to Cart
            </a>

        </div>

        <!-- reviews -->
        <div class="w-full mt-6">
            <h2 class="text-xl">Reviews</h2>
            {% if request.user.is_authenticated %}
            <form method="POST" action="." class="mt-6 mb-6 p6 bg-gray-100 rounded-xl">
                {% csrf_token %}
                <div>
                    <label>Rating</label><br>
                    <select name="rating">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3" selected>3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                    </select>
                </div>

                <div>
                    <label>Comments</label><br>
                    <textarea name="content"></textarea>
                </div>

                <div>
                    <button>Submit</button>
                </div>

            </form>
            {% endif %}

            <!-- Dispaly all reviews -->
            {% for review in product.reviews.all %}
                <div class="px-4 py-6 bg-gray-100 rounded-xl mb-4">
                    <strong>Rating: </strong>{{review.rating }}/6<br>
                    <strong>Created_at: </strong>{{review.created_at|date:"d-m-Y"}}<br>
                    <strong>Comments: </strong><br>
                    {{review.content }}
                </div>
            {% endfor %}
        </div>
    </div>

    {% endblock content %}