Ghome/urls.py

from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',include('core.urls',namespace='core')),
    path('admin/', admin.site.urls),
    path('product/',include('product.urls',namespace='product')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('order/',include('order.urls',namespace='order')),
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import add_to_cart,cart,checkout,hx_menu_cart,update_cart,hx_cart_total,success


app_name='cart'
urlpatterns =[
    path('',cart,name='cart'),
    path('success/',success,name='success'),
    path('checkout/',checkout,name='checkout'),
    path('update_cart/<int:product_id>/<str:action>/',update_cart,name='update_cart'),
    path('<int:product_id>/',add_to_cart,name='add_to_cart'),
    path('hx_menu_cart/',hx_menu_cart,name='hx_menu_cart'),
    path('hx-cart-total/',hx_cart_total,name='hx_cart_total'),
    
]

product/urls.py
from django.urls import path
from . import views


app_name='product'
urlpatterns =[
    path('<slug:slug>/',views.product,name='product'),
    
]

cart/views.py
from django.shortcuts import render
from django.conf import settings
from django.contrib.auth.decorators import login_required
from .cart import Cart
from product.models import Product

# Create your views here.

def add_to_cart(request,product_id):
    cart= Cart(request)
    cart.add(product_id)
    return render(request,'cart/partials/menu_cart.html')

def cart(request):
    cart= Cart(request)

    print(cart)
    for item in cart:
        print(item)
    return render(request,'cart/cart.html')

def success(request):
    return render(request,'cart/success.html')

def update_cart(request,product_id,action):
    cart= Cart(request)

    if action == 'increment':
        cart.add(product_id,1,True)
    else:
        cart.add(product_id,-1,True)
    
    product= Product.objects.get(pk=product_id)
    quantity= cart.get_item(product_id)

    if quantity:
        quantity= quantity['quantity']

        item= {
            'product':{
                'id':product.id,
                'name':product.name,
                'image':product.image,
                'get_thumbnail':product.get_thumbnail(),
                'price':product.price,
            },
            'total_price':(quantity * product.price) / 100,
            'quantity':quantity,
        }
    else:
        item= None
        
    context={'item':item}

    response= render(request,'cart/partials/cart_item.html',context)
    response['HX-Trigger']= 'update-menu-cart'
    return response

@login_required
def checkout(request):
    pub_key= settings.STRIPE_API_KEY_PUBLISHABLE
    context={'pub_key':pub_key}
    return render(request,'cart/checkout.html',context)

def hx_menu_cart(request):
    return render(request,'cart/partials/menu_cart.html')

def hx_cart_total(request):
    return render(request,'cart/partials/cart_total.html')

cart/templates/cart/partials/cart_item.html
{% if item %}
    <div class="product mb-6 flex pr-6" id="cart-item-{{item.product.id}}">
        <a href="{% url 'product:product' item.product.slug %}" class="w-1/4">
            <img class="hover:shadow-lg rounded" src="{{item.product.get_thumbnail }}">
        </a>

        <div class="w-3/4 pl-6">
            <div class="flex justify-between">
                <a href="{% url 'product:product' item.product.slug %}" class="text-lg">{{item.product.name}}</a>
                <span class="mb-6 pt-1 text-gray-400">${{item.total_price }}</span>
            </div>
            <hr>

            <div class="quantity mt-6 flex items-center space-x-4">
                <!-- decrement from cart -->
                <a
                class="p-3 bg-gray-100"
                hx-get="{% url 'cart:update_cart' item.product.id 'decrement' %}"
                hx-target="#cart-item-{{item.product.id}}"
                hx-swap="outerHTML"
                >
                -
                </a>

                <span>{{item.quantity }}</span>
                <!-- increment from cart -->
                <a
                class="p-3 bg-gray-100"
                hx-get="{% url 'cart:update_cart' item.product.id 'increment' %}"
                hx-target="#cart-item-{{item.product.id}}"
                hx-swap="outerHTML"
                >
                +
                </a>
            </div>
        </div>
    </div>
{% endif %}

cart/templates/cart/partials/cart_total.html
${{cart.get_total_cost}}

cart/templates/cart/partials/menu_cart.html

<a href="{% url 'cart:cart' %}" id="menu-cart-button" class="relative">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 00-3 3h15.75m-12.75-3h11.218c1.121-2.3 2.1-4.684 2.924-7.138a60.114 60.114 0 00-16.536-1.84M7.5 14.25L5.106 5.272M6 20.25a.75.75 0 11-1.5 0 .75.75 0 011.5 0zm12.75 0a.75.75 0 11-1.5 0 .75.75 0 011.5 0z" />
      </svg>

    <span class="p-2 absolute -top-4 -right-3 bg-indigo-500 text-white text-xs rounded-full">{{cart|length}}</span>
      
</a>

